-- SUPABASE ADVISORY FIXES SQL SCRIPT

-- 1. Fix Performance Advisories: Missing Indexes on Foreign Keys
CREATE INDEX IF NOT EXISTS "clientdocument_clientcompanyid_idx" ON "public"."ClientDocument"("clientCompanyId");
CREATE INDEX IF NOT EXISTS "contact_clientcompanyid_idx" ON "public"."Contact"("clientCompanyId");
CREATE INDEX IF NOT EXISTS "contentblock_pageid_idx" ON "public"."ContentBlock"("pageId");
CREATE INDEX IF NOT EXISTS "jobapplication_careerjobid_idx" ON "public"."JobApplication"("careerJobId");
CREATE INDEX IF NOT EXISTS "leadnote_leadid_idx" ON "public"."LeadNote"("leadId");
CREATE INDEX IF NOT EXISTS "proposal_clientcompanyid_idx" ON "public"."Proposal"("clientCompanyId");
CREATE INDEX IF NOT EXISTS "proposal_quoterequestid_idx" ON "public"."Proposal"("quoteRequestId");
CREATE INDEX IF NOT EXISTS "proposalitem_proposalid_idx" ON "public"."ProposalItem"("proposalId");
CREATE INDEX IF NOT EXISTS "servicepackage_serviceid_idx" ON "public"."ServicePackage"("serviceId");
CREATE INDEX IF NOT EXISTS "ticket_clientcompanyid_idx" ON "public"."Ticket"("clientCompanyId");
CREATE INDEX IF NOT EXISTS "ticketattachment_ticketid_idx" ON "public"."TicketAttachment"("ticketId");
CREATE INDEX IF NOT EXISTS "ticketmessage_ticketid_idx" ON "public"."TicketMessage"("ticketId");
CREATE INDEX IF NOT EXISTS "user_clientcompanyid_idx" ON "public"."User"("clientCompanyId");
CREATE INDEX IF NOT EXISTS "audit_logs_user_id_idx" ON "public"."audit_logs"("user_id");
CREATE INDEX IF NOT EXISTS "blog_posts_author_id_idx" ON "public"."blog_posts"("author_id");
CREATE INDEX IF NOT EXISTS "blog_posts_category_id_idx" ON "public"."blog_posts"("category_id");
CREATE INDEX IF NOT EXISTS "career_applications_job_id_idx" ON "public"."career_applications"("job_id");
CREATE INDEX IF NOT EXISTS "client_companies_created_by_idx" ON "public"."client_companies"("created_by");
CREATE INDEX IF NOT EXISTS "client_companies_updated_by_idx" ON "public"."client_companies"("updated_by");
CREATE INDEX IF NOT EXISTS "client_company_users_company_id_idx" ON "public"."client_company_users"("company_id");
CREATE INDEX IF NOT EXISTS "client_company_users_user_id_idx" ON "public"."client_company_users"("user_id");
CREATE INDEX IF NOT EXISTS "client_documents_company_id_idx" ON "public"."client_documents"("company_id");
CREATE INDEX IF NOT EXISTS "client_documents_uploaded_by_idx" ON "public"."client_documents"("uploaded_by");
CREATE INDEX IF NOT EXISTS "leads_assigned_to_idx" ON "public"."leads"("assigned_to");
CREATE INDEX IF NOT EXISTS "media_assets_created_by_idx" ON "public"."media_assets"("created_by");
CREATE INDEX IF NOT EXISTS "navigation_items_parent_id_idx" ON "public"."navigation_items"("parent_id");
CREATE INDEX IF NOT EXISTS "notifications_user_id_idx" ON "public"."notifications"("user_id");
CREATE INDEX IF NOT EXISTS "pages_created_by_idx" ON "public"."pages"("created_by");
CREATE INDEX IF NOT EXISTS "profiles_id_idx" ON "public"."profiles"("id");
CREATE INDEX IF NOT EXISTS "quote_requests_company_id_idx" ON "public"."quote_requests"("company_id");
CREATE INDEX IF NOT EXISTS "quote_requests_lead_id_idx" ON "public"."quote_requests"("lead_id");
CREATE INDEX IF NOT EXISTS "service_faqs_service_id_idx" ON "public"."service_faqs"("service_id");
CREATE INDEX IF NOT EXISTS "site_settings_updated_by_idx" ON "public"."site_settings"("updated_by");
CREATE INDEX IF NOT EXISTS "support_tickets_assigned_to_idx" ON "public"."support_tickets"("assigned_to");
CREATE INDEX IF NOT EXISTS "support_tickets_client_id_idx" ON "public"."support_tickets"("client_id");
CREATE INDEX IF NOT EXISTS "support_tickets_company_id_idx" ON "public"."support_tickets"("company_id");
CREATE INDEX IF NOT EXISTS "ticket_messages_ticket_id_idx" ON "public"."ticket_messages"("ticket_id");
CREATE INDEX IF NOT EXISTS "ticket_messages_user_id_idx" ON "public"."ticket_messages"("user_id");
CREATE INDEX IF NOT EXISTS "menu_items_menu_id_idx" ON "public"."menu_items"("menu_id");
CREATE INDEX IF NOT EXISTS "menu_items_parent_id_idx" ON "public"."menu_items"("parent_id");
CREATE INDEX IF NOT EXISTS "footer_links_footer_section_id_idx" ON "public"."footer_links"("footer_section_id");
CREATE INDEX IF NOT EXISTS "page_sections_page_id_idx" ON "public"."page_sections"("page_id");
CREATE INDEX IF NOT EXISTS "survey_requests_client_company_id_idx" ON "public"."survey_requests"("client_company_id");
CREATE INDEX IF NOT EXISTS "survey_responses_survey_request_id_idx" ON "public"."survey_responses"("survey_request_id");
CREATE INDEX IF NOT EXISTS "work_orders_client_company_id_idx" ON "public"."work_orders"("client_company_id");

-- 2. Fix Security Advisories: Missing Row Level Security (RLS)
ALTER TABLE "public"."brand_assets" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on brand_assets" ON "public"."brand_assets" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."menus" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on menus" ON "public"."menus" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."menu_items" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on menu_items" ON "public"."menu_items" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."footer_sections" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on footer_sections" ON "public"."footer_sections" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."footer_links" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on footer_links" ON "public"."footer_links" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."page_sections" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on page_sections" ON "public"."page_sections" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."partner_logos" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on partner_logos" ON "public"."partner_logos" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."trusted_business_logos" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on trusted_business_logos" ON "public"."trusted_business_logos" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."compliance_cards" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on compliance_cards" ON "public"."compliance_cards" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."social_links" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on social_links" ON "public"."social_links" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."survey_settings" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on survey_settings" ON "public"."survey_settings" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."survey_requests" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on survey_requests" ON "public"."survey_requests" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."survey_responses" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on survey_responses" ON "public"."survey_responses" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
ALTER TABLE "public"."work_orders" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff full access on work_orders" ON "public"."work_orders" FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('super_admin', 'admin')));
